# Generated by Django 3.1.6 on 2021-12-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
